### ISSUE TITLE
Sharing Homebrew Race

### ISSUE THREAD

**Issue by Deadboydeath** [TheGiddyLimit/homebrew#1072]
Thought about it, and I want to share a homebrew race. The Mul. Half-Dwarf, Half-Human... I'm not great at coding but... it works. I'm good at copying and pasting :) .

{
	"_meta": {
		"sources": [{
			"json": "GiddyRace",
			"abbreviation": "Brew",
			"full": "TheGiddyLimit",
			"authors": [
				"TheGiddyLimit"
			],
			"version": "1.0.0",
			"url": "https://github.com/TheGiddyLimit/homebrew",
			"targetSchema": "1.0.0"
		}],
		"dateAdded": 0,
		"dateLastModified": 0
	},
	"race": [{
		"name": "Mul",
		"source": "TLE",
		"ability": [{
			"str": 2,
			"con": 1
		}],
		"size": [
			"M"
		],
		"speed": 30,
		"entries": [{
				"type": "entries",
				"name": "Age",
				"entries": [
					"Muls have lifespans comparable to humans. They enter adulthood in their late teens and usually live less than a century."
				]
			},
			{
				"type": "entries",
				"name": "Alignment",
				"entries": [
					"Muls tend towards neutrality with respect to good and evil, but run the gamut with respect to law or chaos. Many lawful muls adapt well to the indignities of slavery, playing the game for the comforts that they can win as valued slaves."
				]
			},
			{
				"type": "entries",
				"name": "Mul Vitality",
				"entries": [
					"Your hit point maximum increases by 1, and it increases by 1 every time you gain a level."
				]
			},
			{
				"name": "Tireless",
				"entries": [
					"As a bonus action, you can shrug off 1 level of exhaustion. You cannot use this trait again until you finish a long rest. You also gain proficiency in the Survival skill."
				],
				"type": "entries"
			},
			{
				"name": "Incredible Toughness",
				"entries": [
					"You can call upon your physical hardiness and dogged determination to withstand any danger or hazard. Using your reaction you can have advantage on a Strength or Constitution saving throw. After you use this trait, you can’t use it again until you finish a short or long rest."
				],
				"type": "entries"
			},
			{
				"name": "Languages",
				"entries": [
					"You can speak Common. You cannot read this language unless a background gives you that trait."
				],
				"type": "entries"
			}
		],
		"fluff": {
			"entries": [
				"Muls are half-dwarves, descended from the union of a human and a dwarf. They have the stature, agility, and mental flexibility of humankind, coupled with the physical resilience and endurance of dwarves—a rare combination of qualities that makes muls more than a simple blend of the two races.Because they are strong, tough, quick, and blessed with fantastic endurance, muls are highly prized as slaves.In fact, most muls are born into slavery."
			]
		},
		"traitTags": [
			"Improved Resting"
		],
		"languageProficiencies": [{
			"common": true
		}]
	}]
}

**Comment by SnortsAlot** [comment]
Please go to the discord and have someone fix this for you.
