### ISSUE TITLE
 KibblesTasty; Artificer (Revised) - Gadgetsmith is missing upgrades table 

### ISSUE THREAD

**Issue by SourKnight** [TheGiddyLimit/homebrew#11]
On the class list, the Gadgetsmith is missing their upgrade table showing all the upgrades they have available, checked the JSON the entries were there, so I assume there is an error in the formatting somewhere, haven't taken an in depth look at it yet.

**Comment by TheGiddyLimit** [comment]
The section (and that of the Wandsmith) have been added as subclass features after 14th level, which doesn't make any sense, and hence they don't show up. Fixed it; will deploy it soon:tm:
