### ISSUE TITLE
Mothfolk race by u/aofhaocv

### ISSUE THREAD

**Issue by Smurph123452zq** [TheGiddyLimit/homebrew#1159]
i needed the mothfolk race for my game so i converted it so i could use it with plutonium. And now I want to submit it so other people on the repository can use it.
original race post: https://www.reddit.com/r/UnearthedArcana/comments/95pr2i/race_mothfolk_an_enigmatic_uncanny_mysterious/

Conversion: https://pastebin.com/EXeTjZqv

**Comment by revilowaldow** [comment]
Closed by #1161 in commit d4d7708

**Comment by revilowaldow** [comment]
Now with fixes!
