### ISSUE TITLE
Homebrew: KibblesTasty's Divine Agent

### ISSUE THREAD

**Issue by bluewarbler** [TheGiddyLimit/homebrew#1198]
I have created a homebrew JSON for KibblesTasty's "Divine Agent" Rogue subclass.  As I barely know how Github operates and don't know how to make a pull request (the how-to link presumes a minimum of knowledge I don't have), I have taken the other option and put it through Pastebin:
https://pastebin.com/um5XpwnJ
I've checked it with JSON Lint and put the file into 5eTools manually, and it seems to work just fine.

**Comment by revilowaldow** [comment]
Closed by #1199
