### ISSUE TITLE
[Suggestion] Import homebrew from other people's repositories

### ISSUE THREAD

**Issue by Trokkin** [TheGiddyLimit/homebrew#1240]
Having to make PRs / Issues to resolve by hand seems to be a lot of trouble. I think it can be made to automatically collect homebrew from a list of external repositories. It is especially good if someone's developing their homebrew and frequently updates it.

I acknowledge the result might not be worth the trouble, though, but the idea is probably worth considering.

**Comment by TheGiddyLimit** [comment]
Not a fan. If someone wants to submit a brew, they can PR it; at the end of the day, even if someone wants to submit hundreds of files, it's still one commit/one PR. If a repository is a fork of this one, it's one button click. If it's _not_ a fork, this implies it's a custom/specific enough case that I wouldn't want to script/automate taking brews from it anyway.

Beyond that, crawling other repos for brews is bad form. Additionally, these may be "private" brews, these may be custom versions of "official" brews, these may be WIPs, translations, etc. etc. Keeping it "opt-in" ensures that people only submit (at least what they think is) appropriate content. The barrier to entry is already very low.

**Comment by SnortsAlot** [comment]
I'll add that the site includes the ability for users to swap around between repos - 
If someone is doing their own repo with changes etc, that's (to my knowledge) was the intended workflow - the merge with main repo and gitignore the things they don't want to share ( 🥺 ) while getting upstream versions of the rest.

One of the concerns I would have is customized versions of different content and the merge issues from crawling the repos for their content... 

In process work (personal example) may be part of their repo, and then bad code replaces good, or 10 people have different versions of a file.

Would also suggest, that suggestions are best done in the discord group
