### ISSUE TITLE
Homebrew Wandering Blademaster Subclass

### ISSUE THREAD

**Issue by FlexTapeNr1** [TheGiddyLimit/homebrew#1255]
Fighter Martial Archetype utilizing wind to crowd control and use advantage to instead deal bonus damage, I would like it to be here :)
[Wandering Blademaster Subclass.zip](https://github.com/TheGiddyLimit/homebrew/files/8112463/Wandering.Blademaster.Subclass.zip)

**Comment by revilowaldow** [comment]
Closed by #1261
