### ISSUE TITLE
Dragonstew Homebrew

### ISSUE THREAD

**Issue by Revulous** [TheGiddyLimit/homebrew#1470]
Hi, first, I'm really sorry. It's like 3am, I just got off work, and I'm trying to figure out how to convert this pdf to json and I'm near pulling my hair out. Delete this if it's not okay, I'll understand. 

https://drive.google.com/file/d/1DxPTdklVMaYCEntl8ujvOd9LVfGnMwJ_/view?usp=sharing

**Comment by revilowaldow** [comment]
You can get help in the brew conversion channel in the community discord https://discord.gg/5etools
