### ISSUE TITLE
Kibbles Tasty Psion

### ISSUE THREAD

**Issue by MechanicBovine** [TheGiddyLimit/homebrew#1580]
I noticed Kibbles Tasty Psion had some errors where certain subclass features didn't appear when their subclass was selected.

Heres a json with corrections
[kibbles psion](https://drive.google.com/file/d/15NFYKJPDKwAJ-_0R6sBtaB5jKAlfHy_7/view?usp=drivesdk)

**Comment by revilowaldow** [comment]
Closed by #1581

**Comment by revilowaldow** [comment]
@TheGiddyLimit This issue can now be closed.
