### ISSUE TITLE
Tidy 5e Sheet pop out 

### ISSUE THREAD

**Issue by Nysterian** [TheGiddyLimit/homebrew#1593]
The module [Tidy5e Sheet](https://github.com/sdenec/tidy5e-sheet) has recently updated, and with the update, whenever I use the popout sheet button that Plutonium provides, if I have the dark mode selected, the popped out sheet will not be in dark mode.

I didn't know whether to report this here or in the Tidy5e Sheet github, but since the popout button is something provided by the Plutonium mod, I thought I'd ask here first, and ask there later if this isn't a thing that Plutonium can fix

**Comment by TheGiddyLimit** [comment]
The [Discord](https://discord.gg/nGvRCDs) is the preferred place for bug reports, this repo has unrelated to Tidy5e/Plutonium

Fixed for next release all the same, ty
