### ISSUE TITLE
Homebrew Addition: Advanced Undead

### ISSUE THREAD

**Issue by LornestFluke** [TheGiddyLimit/homebrew#1836]
Lornesflukes Advanced Undead
adds a book, creatures, a subclass, items, a race, a background, spells, and a legendary group, all themed around or related to undead or immortality.
Gist: https://gist.github.com/LornestFluke/79176f82af73f6832344bb2d70df71c2

**Comment by revilowaldow** [comment]
Fixes:

- Ran Cleaner
- Colour typo
- Added `_meta` required properties
- Fixed list style information in bookdata
- Removed empty image placeholders
- Fixed italic tag in Continual Flame
- Fixed Osteolon `type` information
- Fixed Sheaf `speed` information
- Added missing entry types in Graven Image Variant information
- Added missing entry type in Spatial Twist higher levels text
- All of the below is invalid, but you already seem to have valid skill/save information. So it has been removed to pass the tests.
![image](https://github.com/TheGiddyLimit/homebrew/assets/52298102/82829d5e-cefa-46e8-a801-20b0798f2dc2)

**Comment by revilowaldow** [comment]
You can see the fixes here: https://github.com/TheGiddyLimit/homebrew/pull/1837/commits/dd0e77546bc68dfd4c35c22a05ba348284d42e5c?diff=unified&w=1

I suggest using the "hide whitespace" while looking at what changed.
![image](https://github.com/TheGiddyLimit/homebrew/assets/52298102/91b28d52-5f98-46b3-8407-97825894ffeb)

**Comment by LornestFluke** [comment]
thank you very much

**Comment by revilowaldow** [comment]
No problem 🙂
