### ISSUE TITLE
LaserLlama's Vessel Class

### ISSUE THREAD

**Issue by E2Gaming** [TheGiddyLimit/homebrew#2054]
Since LaserLlama's other homebrew classes were already here I decided to convert the only one that wasn't.
https://pastebin.com/VyUeDgTN

**Comment by hakr14** [comment]
Sorry for my late (*very* late) reply! I'm gonna be going over all the LaserLlama jsons, and I think a good compromise will be to use E2's conversion as a base (completely wiping mine) and going from there. It'll be a bit before that happens though... for now my vote is to just use @E2Gaming's.
