### ISSUE TITLE
Justice Arman; Devil's Advocate A Guide to Infernal Contracts - Illegal Characters 

### ISSUE THREAD

**Issue by MrRootKitty** [TheGiddyLimit/homebrew#2070]
json's json code name contained ":"

Changing it to just DAGIC seemed to fix the CLI process. 

![image](https://github.com/TheGiddyLimit/homebrew/assets/25812275/37278493-a908-4d79-9f92-a2d812a907f0)

**Comment by MrRootKitty** [comment]
[Justice Arman; Devil's Advocate A Guide to Infernal Contracts.json](https://github.com/TheGiddyLimit/homebrew/files/14851185/Justice.Arman.Devil.s.Advocate.A.Guide.to.Infernal.Contracts.json)

**Comment by revilowaldow** [comment]
Lots of JSON ids contain special characters. 
Based on your screenshot you look like you're probably using the obsidian module. 
Please report your issues there: https://github.com/ebullient/ttrpg-convert-cli/
