### ISSUE TITLE
HGtMH - Illegal Characters 

### ISSUE THREAD

**Issue by MrRootKitty** [TheGiddyLimit/homebrew#2071]
![image](https://github.com/TheGiddyLimit/homebrew/assets/25812275/0460b16c-2b39-4b90-880e-f173c80c12f9)

**Comment by revilowaldow** [comment]
Again, issues with the obsidian tool to be reported there: https://github.com/ebullient/ttrpg-convert-cli/

**Comment by ebullient** [comment]
This is a CLI issue. yes. Just close this.
