### ISSUE TITLE
Homebrew Conversion (Kobold Press Deep Magic)

### ISSUE THREAD

**Issue by hafdon** [TheGiddyLimit/homebrew#283]
e.g. __Maddening Whispers__
(found in Doomsayer in Creature Codex)

Creature Codex references Deep Magic spells but their homebrew is not in repo

http://kpogl.wikidot.com/spell:maddening-whispers
https://koboldpress.com/kpstore/product/deep-magic-void-magic-pdf-5th-edition/

**Comment by p4535992** [comment]
@TheGiddyLimit this issue is solved right ?

**Comment by TheGiddyLimit** [comment]
Probably.
