### ISSUE TITLE
Schema for adding traits without having to attach them to creatures.

### ISSUE THREAD

**Issue by hafdon** [TheGiddyLimit/homebrew#289]
from the discord

hafdon Yesterday at 11:51 PM
I see that creature traits are indexed so they show up in the [Add Predefined Traits] modal in the  makebrew. Is there a way to add traits without attaching them to creatures?
 
SupportToday at 12:09 AM
That's kinda what I'm working on getting to Giddy - a list of all the traits /etc for them from all the sources

**Comment by DMsGuild201** [comment]
There is a suggestion voting element for this, you would want to go to the discord and vote on this to raise its priority.

**Comment by hafdon** [comment]
Very cool, thanks -- however, I couldn't find it when I looked.

Also, should I refrain from opening issues here like this and only mention them on discord?

**Comment by TheGiddyLimit** [comment]
> Also, should I refrain from opening issues here like this and only mention them on discord?

Generally, yes. Lodging them as a suggestion there is much preferred
