### ISSUE TITLE
Adding a subclass.

### ISSUE THREAD

**Issue by Nad12985** [TheGiddyLimit/homebrew#29]
Not git-literate, so here is my pastebin link.
https://pastebin.com/rfSWuRud

Just one of the subclasses from the Codex of Allies.
https://www.dmsguild.com/product/243863/Mordenkainens-Codex-of-Allies

**Comment by TheGiddyLimit** [comment]
Lovely; added. Changed the source/named the file to be the full book, in case anyone decides to expand it in future.
