### ISSUE TITLE
The race "Zagorath; Vryloka.json" appear on the list but not show the checkbox for the import

### ISSUE THREAD

**Issue by p4535992** [TheGiddyLimit/homebrew#322]
The race "Zagorath; Vryloka.json" appear on the list but not show the checkbox for the import.
It's surely some stupid error i made on the json.
I wasn't enable to find the error.
Can you help me to find the error?
Greetings.

**Comment by TheGiddyLimit** [comment]
Checkbox for import..? Where are you expecting to see this?

**Comment by p4535992** [comment]
Sorry, make some screenshot to make the problem" more clear.
I' going to select import "Races" for exampe the mousefolk another homebrew .

0) I go to roll20 with 5etolls installed

1) Select to import race

![Races](https://i.imgur.com/WJ1wccv.png)

2) Chooose a rcae "mousefolk" for example

![Mousefolk](https://i.imgur.com/NHkVd1y.png)

3) Select the checkbox and import the race handout

![CMousefolk](https://i.imgur.com/bjnxriM.png)

4) Now i select my Vryloka race

![Vryloka](https://i.imgur.com/AlB4AY6.png)

5) But i can't see the checkbox for the import

![CVryloka](https://i.imgur.com/MwYN6Go.png)

No checkbox? I messed up with the json .

Any help is more than welcome ty.

**Comment by TheGiddyLimit** [comment]
Perfect. Fixed it; you had an empty `"subraces": []` array in there, which prevents the base race from being shown (as it is assumed to have subraces and therefore be "incomplete" on its own).

**Comment by TheGiddyLimit** [comment]
The fact that it does that is a bug, which has also been fixed for next release of the main site.

**Comment by p4535992** [comment]
Hi, success!
dont' know what did you do, but now i can see the checkbox and import the handout

![vryloka_checkbox](https://i.imgur.com/5lQtrgr.png)

the only problem is i see the handout blank XD

![vryloka_handout](https://i.imgur.com/2vZlSIF.png) 

is this still a bug? or something i messed up on the json?
ty for your help.

**Comment by TheGiddyLimit** [comment]
😒 yes, the ability scores were invalid. That should now be fixed too.

**Comment by p4535992** [comment]
Ok i see on the other race is not


```
"ability": {
				"cha": 2,
				"choose": [
					{
						"from": [
							"dex",
							"str"
						],
						"count": 1
					}
				]
			},
```
it must be 

```
			"ability": {
				"cha": 2,
				"choose": {
						"from": [
							"dex",
							"str"
						],
						"count": 1
					}
				
			},

```

i'll make a pull to fix this
