### ISSUE TITLE
Enrichment of the "homebrew builder"

### ISSUE THREAD

**Issue by p4535992** [TheGiddyLimit/homebrew#348]
This is not a bug, it is just an enrichment of the "homebrew builder" that I would like to have integrated but it is more a desire than anything else.

On the "Abilities" tab on the spellcasting trait the possibility to set info about:

Spellcasting Ability (None,Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma) (String)
Global Magic Attack Modifier (Integer)
Magic Caster Level (String)
Spell Save DC Mod (Integer)

for a better Roll20 integration.

On the "Abilities" tab on the actions trait for the generate attack add a "Description" text of the saving throw on weapon.

For example :

Ranged Weapon Attack: +5 to hit. range 30/120 ft., one creature. Hit: 6 (1d6 + 3) piercing damage and the target must succeed on a DC 13 Constitution saving throw or be poisoned for 1 hour. If the saving throw fails by 5 or more, the target is also unconscious while poisoned in this way. The target wakes up if it takes damage or if another creature takes an action to shake it awake.

Greetings.

**Comment by TheGiddyLimit** [comment]
I'm afraid the Roll20 integration is deprecated/maintenance only. Even were it not, I would be hesitant to "pollute" the site's homebrew builder with things not intended for use on the site.
