### ISSUE TITLE
Psions Primer and Threat Dispatch Update

### ISSUE THREAD

**Issue by Biggoron144** [TheGiddyLimit/homebrew#439]
https://gist.github.com/Biggoron144/b3c01549091f97d1a8350bf51c23ce46
https://gist.github.com/Biggoron144/a7699fdecc020375390adeb2e871af60

Sorry, exceeded size of pastebin...

**Comment by TheGiddyLimit** [comment]
Glorious, ty

**Comment by Biggoron144** [comment]
Revised psions primer with some bugfixes; would you please update it from the gist link above.

![image](https://user-images.githubusercontent.com/36545366/83298969-fbe06e80-a1ba-11ea-9020-87b0efc2f353.png)

And there is now two of these Threat Dispatch files if you want to remove the older one

**Comment by TheGiddyLimit** [comment]
👍
