### ISSUE TITLE
Lingering soul class' phantom calling features at wrong levels

### ISSUE THREAD

**Issue by sheep-19** [TheGiddyLimit/homebrew#455]
When selected either of three Lingering soul's subclasses it's features shows at wrong levels. It's expected to have a phantom calling feature at 1st, 6th, 11th and 15th levels but appears at 6th, 11th, 15th and 18th, even when the feature description says at what level it suppose to be.
I mean I'm reading 6th lvl and feature be like "no bro it's 1st".

**Comment by TheGiddyLimit** [comment]
Thanks bro, fixed
