### ISSUE TITLE
Homebrew Conversion for Beauty and the Bother

### ISSUE THREAD

**Issue by CuddlyKhan** [TheGiddyLimit/homebrew#56]
https://pastebin.com/aCKmr7sS

Hoping I did everything right. Couldn't figure out how to do a pull request.

**Comment by TheGiddyLimit** [comment]
Near-perfect; `convertedBy` is supposed to be an array, but it seems we've plenty examples where that's wrong anyway 😂

**Comment by CuddlyKhan** [comment]
Cool, thanks. Gonna see if I can convert some more books or even some adventures.
