### ISSUE TITLE
Homebrew Conversions: Walrock Homebrew's Witch and Jonoman3000's Planeshifter

### ISSUE THREAD

**Issue by MobiusFlip** [TheGiddyLimit/homebrew#562]
Don't know how to make a pull request, so I'm submitting these conversions here.

[WalrockHomebrewWitch](https://pastebin.com/4bi4n1h1)
[JonomanPlaneshifter](https://pastebin.com/DB6Ae2ci)

**Comment by TheGiddyLimit** [comment]
Will add, thanks
