### ISSUE TITLE
Homebrew Upload Request

### ISSUE THREAD

**Issue by Biggoron144** [TheGiddyLimit/homebrew#623]
Hello,

https://pastebin.com/w4StV8mA

Please go ahead and add this to the repository!

**Comment by TheGiddyLimit** [comment]
It's been in the repository since mid December 2019; right [here](https://github.com/TheGiddyLimit/homebrew/blob/master/feat/ImFromNASA%3B%20Talent%20Trees.json).

**Comment by TheGiddyLimit** [comment]
On closer inspection, yours has slightly more content than the previous version (although they both reference the same source file, and have the same version; go figure). I've merged the two together, so the above link should now be to your updated version.
