### ISSUE TITLE
Adding OotD

### ISSUE THREAD

**Issue by dinosaurwave** [TheGiddyLimit/homebrew#630]
https://www19.zippyshare.com/v/6iD6gcmb/file.html
I've uploaded the JSON file to here. Just took exported the module to a JSON. I'm completely GitHub illiterate so I hope someone else can check over this and edit it.
thanks

**Comment by TheGiddyLimit** [comment]
That link 403's for me--try opening it in an incognito window on your end to make sure it's shareable.

**Comment by Spappz** [comment]
Just so you know: Zippyshare blocks UK IPs. VPNs can get around it easily (or just use another filehoster).

Also worth noting that Zippyshare deletes files that receive no downloads for 30 days.
