### ISSUE TITLE
Swordmage Homebrew Class 

### ISSUE THREAD

**Issue by Biggoron144** [TheGiddyLimit/homebrew#687]
https://pastebin.com/nk6kSAVn

For addition to repository

**Comment by TheGiddyLimit** [comment]
Cheers.

**Comment by Biggoron144** [comment]
Hmm. Don't actually see it added. It is different than the current swordmage homebrew in the repository, if you noted that and thought it was a duplicate.

**Comment by TheGiddyLimit** [comment]
No, I just hadn't got around to actually adding it. Should be up now.
