### ISSUE TITLE
Adding a Subclass: Way of the Four Elements Remastered

### ISSUE THREAD

**Issue by OftheGates** [TheGiddyLimit/homebrew#69]
Not terribly Git-literate, so I'm posting this here:

https://raw.githubusercontent.com/OftheGates/DnD-Homebrew/master/Wot4E_Remastered

This is the revision of Way of the Four Elements created by SpiketailDrake and IrishBandit with the help of the subreddit r/UnearthedArcana, shown here:

https://drive.google.com/file/d/0B5ttoyMfsaC7eFhVenpwZ0R4ZmM/view?usp=sharing

**Comment by DMsGuild201** [comment]
one less item on the todo list! thank you Ofthegates

**Comment by TheGiddyLimit** [comment]
Cheers, added.
