### ISSUE TITLE
Two Classes for addition

### ISSUE THREAD

**Issue by Biggoron144** [TheGiddyLimit/homebrew#692]
Benjamin Huffman; Spiritualist.json
https://pastebin.com/cCtitsZh

Benjamin Huffman; Scholar.json
https://pastebin.com/Fn4vUxyu

Thanks!

**Comment by Biggoron144** [comment]
[classes.zip](https://github.com/TheGiddyLimit/homebrew/files/5578198/classes.zip)

**Comment by TheGiddyLimit** [comment]
Thank you
