### ISSUE TITLE
Flavor Text for items

### ISSUE THREAD

**Issue by tylermac** [TheGiddyLimit/homebrew#70]
Request to support allowing fluff for items to add possible description, history, flavour text, and/or an image for magic items.

**Comment by TheGiddyLimit** [comment]
A planned feature, although it was more of a long-term plan (as the idea was to add all the WotC item images, and perhaps descriptions, at the same time). I could certainly implement the homebrew half fairly quickly; I'll see if I can do that this week (although when that'll be deployed is more of an unknown, we're having some server-transition woes at the moment).
