### ISSUE TITLE
Bronze Automaton from Odyssey of the Dragonlords

### ISSUE THREAD

**Issue by DudeAndre** [TheGiddyLimit/homebrew#702]
{
	"_meta": {
		"sources": [
			{
				"json": "ArcanumWorldsOdysseyoftheDragonlords",
				"abbreviation": "OotD",
				"full": "Arcanum Worlds; Odyssey of the Dragonlords",
				"url": "https://www.dmsguild.com/product/285960/Odyssey-of-the-Dragonlords-Adventure-Book",
				"authors": [
					"James Ohlen",
					"Jesse Sky"
				],
				"convertedBy": [
					"TheDude"
				]
			}
		],
		"dateAdded": 1606277012,
		"dateLastModified": 1606277012
	},
	"monster": [
		{
			"name": "Bronze Automaton",
			"source": "ArcanumWorldsOdysseyoftheDragonlords",
			"page": 364,
			"size": "M",
			"type": "construct",
			"alignment": [
				"U"
			],
			"ac": [
				{
					"ac": 17,
					"from": [
						"natural armor"
					]
				}
			],
			"hp": {
				"formula": "8d8 + 24",
				"average": 60
			},
			"speed": {
				"walk": 30
			},
			"str": 16,
			"dex": 10,
			"con": 16,
			"int": 9,
			"wis": 10,
			"cha": 10,
			"save": {
				"str": "+3",
				"con": "+3",
				"int": "-1"
			},
			"senses": [
				"darkvision 120 ft."
			],
			"passive": 10,
			"immune": [
				"lightning",
				"poison",
				"psychic"
			],
			"conditionImmune": [
				"charmed",
				"exhaustion",
				"frightened",
				"paralyzed",
				"petrified",
				"poisoned"
			],
			"languages": [
				"Speak the languages of its creator"
			],
			"cr": "4",
			"trait": [
				{
					"name": "Death Throes",
					"entries": [
						"When the bronze automaton dies, there is a 50% chance that it explodes in a conflagration of fire and lightning. Each creature within 5 feet of it must make a {@dc 15} Dexterity saving throw, taking 17 ({@damage 5d6}) fire damage and 17 ({@damage 5d6}) lightning damage on a failed save, or half as much on a successful one."
					]
				},
				{
					"name": "Immutable Form",
					"entries": [
						"The bronze automaton is immune to any spell or effect that would alter its form."
					]
				},
				{
					"name": "Magic Resistance",
					"entries": [
						"The bronze automaton has advantage on saving throws against spells and other magical effects."
					]
				},
				{
					"name": "Magic Weapons",
					"entries": [
						"The bronze automaton's weapon attacks are magical"
					]
				},
				{
					"name": "Martial Advantage",
					"entries": [
						"Once per turn, the bronze automaton can deal an extra 10 ({@damage 3d6}) damage to a creature it hits with a weapon attack if that creature is within 5 feet of an ally of the bronze automaton that isn't {@condition incapacitated}."
					]
				}
			],
			"action": [
				{
					"name": "Multiattack",
					"entries": [
						"The bronze automaton makes two glaive attacks."
					]
				},
				{
					"name": "Glaive",
					"entries": [
						"{@atk mw} {@hit 6} to hit, reach 10 ft., one target. {@h}9 ({@damage 1d10 + 3}) slashing damage."
					]
				}
			],
			"fluff": {
				"entries": [
					"Bronze automatons are constructed using mechanical and magical techniques that are passed down by the gods. They are built for war and little else. They need constant repairs and maintenance or else they begin to break down. This means that they cannot be left as unattended guardians for longer than a few years.",
					"Constructed Nature. Bronze automatons are the ultimate soldiers. They don’t age, and they don’t need air, food, drink, or sleep. They are built for the sole purpose of fighting until they are destroyed.",
					"Explosive Power. Bronze automatons are powered by a mixture of elemental fire and bottled lightning. When an automaton is destroyed, this mixture of elemental energy can be released in the automaton’s death throes with catastrophic results to anyone standing close to them. Luckily, bronze automatons are immune to lightning and resistant to fire, otherwise these explosions might lead to chain reactions that could obliterate an entire legion of the automatons."
				]
			},
			"tokenUrl": "https://imgur.com/SFU7kV5",
			"traitTags": [
				"Death Burst",
				"Immutable Form",
				"Magic Resistance",
				"Magic Weapons"
			],
			"senseTags": [
				"SD"
			],
			"actionTags": [
				"Multiattack"
			],
			"damageTags": [
				"F",
				"L",
				"S"
			],
			"miscTags": [
				"AOE",
				"MW",
				"RCH"
			]
		}
	]
}
![Bronze Automaton](https://user-images.githubusercontent.com/68960682/100182442-e2577f80-2edc-11eb-8ed2-d7b3516600c0.png)
![Brone Automaton](https://user-images.githubusercontent.com/68960682/100182444-e4214300-2edc-11eb-852f-2a84ea228468.jpg)

**Comment by TheGiddyLimit** [comment]
Added.
