### ISSUE TITLE
Homebrew Conversion: Oath of the Templar by FallenPhoenixIV on DnD Beyond

### ISSUE THREAD

**Issue by andriantimeswift** [TheGiddyLimit/homebrew#736]
https://pastebin.com/t4v56M7i

**Comment by TheGiddyLimit** [comment]
Cheers, added.

**Comment by andriantimeswift** [comment]
https://pastebin.com/nWURkxx2

I made a mistake in the original file that caused errors in Plutonium, so this is a fixed version
