### ISSUE TITLE
Reverting: ImFromNASA; Talent Trees.json

### ISSUE THREAD

**Issue by Maalunar** [TheGiddyLimit/homebrew#739]
https://github.com/TheGiddyLimit/homebrew/commits/master/feat/ImFromNASA%3B%20Talent%20Trees.json
I would like to see this file reverted to its Commits on Jan 24, 2020 version. Some changes somebody made it deviated from the original pdf. I have an update to Sasquatchbrah's "deviant" version ready which I'll make a pull request to upload separately from this one after the reversion.

**Comment by TheGiddyLimit** [comment]
👍 reverted, ty
