### ISSUE TITLE
New Homebrew Class - Scion

### ISSUE THREAD

**Issue by DrunkenYoda** [TheGiddyLimit/homebrew#905]
Main Scion class JSON File: https://drive.google.com/file/d/1huOc8HoB0SuS5etBBxK2WUW2jnbowrp_/view

Contains a new class and 6 new spells for it.

**Comment by DrunkenYoda** [comment]
New spells: https://pastebin.com/kK8CnKSE

**Comment by TheGiddyLimit** [comment]
Added, thanks
