### ISSUE TITLE
Request homebrew upload

### ISSUE THREAD

**Issue by Fuffy-Katons** [TheGiddyLimit/homebrew#953]
I understand that if I would like my homebrew to be uploaded to the 5e.tools website I should make an issue here so that is what I'm doing. Can I please get this homebrew uploaded. below is a PasteBin link and raw. 

https://pastebin.com/raw/Gn0P4GmC

https://pastebin.com/Gn0P4GmC

**Comment by TheGiddyLimit** [comment]
Almost--it's preferred if you make a Pull Request to directly add the files. If you click "Add File" at the top of the repo, it should guide you through.

**Comment by Fuffy-Katons** [comment]
ok ill do that thx
